### ISSUE TITLE
RN 退出重新进入

### ISSUE THREAD

**Issue by liu868588** [sunnylqm/react-native-storage#128]
在AlarmBottomView组件中进行保存和读取没有问题。但是退出APP(杀掉进程)，再进入就读取不到了。
但是我如果把实例化和写入和读取都写在一个index.android.js里面就没有问题
![dnt l9zzmz220b ztv bc0](https://user-images.githubusercontent.com/10568931/30322564-79525e0e-97ec-11e7-8ad7-fa373e0cafcd.png)

![r i3_0n ix b yl yc2 ex](https://user-images.githubusercontent.com/10568931/30322361-d060210a-97eb-11e7-81a4-72e86c5d1311.png)

![yao 2jm vnx8tg1pgypm g](https://user-images.githubusercontent.com/10568931/30322393-ec7155bc-97eb-11e7-93de-ab7e6638ccb9.png)

**Comment by sunnylqm** [comment]
你要注意import的顺序Sent from my Huawei Mobile-------- Original Message --------Subject: [sunnylqm/react-native-storage] RN 退出重新进入 (#128)From: liu868588 To: sunnylqm/react-native-storage CC: Subscribed 在AlarmBottomView组件中进行保存和读取没有问题。但是退出APP(杀掉进程)，再进入就读取不到了。
但是我如果把实例化和写入和读取都写在一个index.android.js里面就没有问题




—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sunnylqm/react-native-storage","title":"sunnylqm/react-native-storage","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sunnylqm/react-native-storage"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"RN 退出重新进入 (#128)"}],"action":{"name":"View Issue","url":"https://github.com/sunnylqm/react-native-storage/issues/128"}}}

**Comment by liu868588** [comment]
如上图所示，我的import是放在index.android.js里面的，相当于一进来就加载了啊。这样不行吗？

**Comment by sunnylqm** [comment]
我注意到你放在17行，那么17行之前的都是用不了的

**Comment by liu868588** [comment]
你的意思就是放在最前面是吧，但是我刚刚试了，还是不行呢。

![_v7_ eqd_jw r3 i17 n](https://user-images.githubusercontent.com/10568931/30356284-b7191376-986a-11e7-9f2c-5eb0a9c33079.png)

**Comment by sunnylqm** [comment]
请仔细看文档，你没有指定backend

**Comment by liu868588** [comment]
十分感谢，看来以后得看官方的
