### ISSUE TITLE
clearMapForKey方法无法清除数据

### ISSUE THREAD

**Issue by wlfcss** [sunnylqm/react-native-storage#133]
![error2](https://user-images.githubusercontent.com/12138285/31275129-86efbc7a-aac8-11e7-9735-0a1cac9b62e7.png)
![error1](https://user-images.githubusercontent.com/12138285/31275132-889decea-aac8-11e7-8342-5d8f69228948.png)
![error3](https://user-images.githubusercontent.com/12138285/31275136-8acbb18c-aac8-11e7-8b07-106ee4878997.png)
使用Fetch获取数据后执行储存，使用clearMapForKey无法清除数据值？

**Comment by sunnylqm** [comment]
请说明具体流程，预期结果和实际结果

**Comment by acidSnakerj** [comment]
I had the same issue. Let me explain.

My structure was this:
```javascript
     storage.save({
        key: 'user',
        data: // Some data I must save
      });
```
### Expected result
- When I push a button to go a another component the info of the storage is deleted, to do this  I use `storage.clearMapForKey('user')`.

### Real result
- When I use the button the info continue in the storage.

### What I did to solve this:
 - Instead of `clearMapForKey`or `clearMap`Methods I used `storage.remove({ key: 'user' });`. Now when I push the button the info is deleted from the storage.

I dont know if this is the best solution for this, only I could with this.

### Additionaly
- My structure to load 
```javascript
     this.props.storage.load({
       key: 'user',
       autoSync: false,
       syncInBackground: false,
    }).then(ret => {
        console.log(ret.userid);
    }).catch(err => {
      // any exception including data not found
      // goes to catch()
      console.warn(err.message);
      switch (err.name) {
        case 'NotFoundError':
          break;
        case 'ExpiredError':
          break;
        default:
          break;
      }
    });
  }
```

**Comment by sunnylqm** [comment]
@acidSnakerj 
Thanks for the detailed explanation.
I need to clarify that `clearMapForKey` is only for `key-id` data.
