### ISSUE TITLE
[Question] Does it work in React?

### ISSUE THREAD

**Issue by MetCoder95** [sunnylqm/react-native-storage#162]
I'm working on two projects in parallel, one for web and the last for mobile.

Can I use without any problems?

**Comment by grean** [comment]
I've tried to use it with a [CRA](https://github.com/facebook/create-react-app/blob/master/README.md#getting-started) app V1.0.17  for browser purpose but i get this error message at compilation : 
```
./node_modules/react-native-storage/storage.js
Module parse failed: Unexpected token (186:41)
You may need an appropriate loader to handle this file type.
|     if(this.enableCache && this.cache[key] !== undefined) {
|       ret = this.cache[key];
|       return this._loadGlobalItem({ ret, ...params });
|     }
|     return this.getItem(key).then(ret => this._loadGlobalItem({ ret, ...params }));
```
In my code, i use it like this : 
```
import Storage from 'react-native-storage';

window.storage = new Storage({
	// maximum capacity, default 1000 
	size: 1000,

	// Use AsyncStorage for RN, or window.localStorage for web.
	// If not set, data would be lost after reload.
	storageBackend: window.localStorage,
	
	// expire time, default 1 day(1000 * 3600 * 24 milliseconds).
	// can be null, which means never expire.
	defaultExpires: 1000 * 3600 * 24,
	
	// cache data in the memory. default is true.
	enableCache: false,
	
	// if data was not found in storage or expired,
	// the corresponding sync method will be invoked and return 
	// the latest data.
	sync : {
		// we'll talk about the details later.
	}
});
```

However, CRA app uses babel and all great new JS stuff like arrow function and others. For now, i don't know how to modify the webpack configuration of the CRA app to make it working. I think Sunny should try to make this package compatible to react-scripts package.

Otherwise react-native part works fine, thanks !

**Comment by sunnylqm** [comment]
One simple solution is to copy the source code into your own project (not in node_modules) to use.
I'll make a precompiled version later this month so you don't have to do any configuration.

**Comment by skizzo** [comment]
Can be solved using [these settings in webpack](https://github.com/sunnylqm/react-native-storage/issues/66#issuecomment-313281947).
