### ISSUE TITLE
cannot yarn add @types/react-native-storage

### ISSUE THREAD

**Issue by yamato-payforward** [sunnylqm/react-native-storage#198]
I did `yarn add @types/react-native-storage`

I got this error.

error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-native-firebase: Not found".

help me.

**Comment by sunnylqm** [comment]
No types for this lib yet. Will publish laterSent from my Huawei Mobile-------- Original Message --------Subject: [sunnylqm/react-native-storage] cannot yarn add @types/react-native-storage (#198)From: yamato-payforward To: sunnylqm/react-native-storage CC: Subscribed I did yarn add @types/react-native-storage
I got this error.
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-native-firebase: Not found".
help me.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sunnylqm/react-native-storage","title":"sunnylqm/react-native-storage","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sunnylqm/react-native-storage"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"cannot yarn add @types/react-native-storage (#198)"}],"action":{"name":"View Issue","url":"https://github.com/sunnylqm/react-native-storage/issues/198"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sunnylqm/react-native-storage/issues/198",
"url": "https://github.com/sunnylqm/react-native-storage/issues/198",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "cannot yarn add @types/react-native-storage (#198)",
"sections": [
{
"text": "",
"activityTitle": "**yamato-payforward**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yamato-payforward",
"facts": [
{
"name": "Repository: ",
"value": "sunnylqm/react-native-storage"
},
{
"name": "Issue #: ",
"value": 198
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sunnylqm/react-native-storage\",\n\"issueId\": 198,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sunnylqm/react-native-storage\",\n\"issueId\": 198\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/sunnylqm/react-native-storage/issues/198"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383698773\n}"
}
],
"themeColor": "26292E"
}
]
