### ISSUE TITLE
What happens when maximum storage size fills up?

### ISSUE THREAD

**Issue by sbefort** [sunnylqm/react-native-storage#32]
Also, I'm assuming the default of 1000 is 1MB, correct?  Is there any way to query the current database size during development so we have an idea of how much space we actually need to allocate for production?

**Comment by sunnylqm** [comment]
There is no easy way to calculate the current size of database(I'll consider to sum the string size everytime when save method invoked in future versions), and that's why I limit it in number. When maximum size fills up, it will loop over(the 1001th will overwrite the 1st, and the 1st is gone, so make sure the "key-id" data is not so important). So no exact maximum space is warranted, just not infinite.

**Comment by sbefort** [comment]
So the maximum default size is 1000 key-value pairs and not 1000 kilobytes?  Is that correct?

**Comment by sunnylqm** [comment]
Yep.
